require("config.lazy")
require("config.autocmds")
require("config.keymaps")
require("config.options")
require("config.lsp")
require("config.dap")
require("config.statuscol")
require("config.lsp.jdtls")
